POST {{host}}/_add HTTP/1.1
Authorization: Basic {{auth}}
Content-Type: application/json

{
  "url": "https://github.com",
  "short_tag": "github"
}

###

GET {{host}}/_stats HTTP/1.1
Authorization: Basic {{auth}}
