POST /_add HTTP/1.1
Host: localhost:4002
Authorization: Basic dXNlcjpwYXNzd29yZA==
Content-Type: application/json
Content-Length: 58

{
  "url": "https://github.com",
  "short_tag": "github"
}

###

GET /_stats HTTP/1.1
Host: localhost:4002
Authorization: Basic dXNlcjpwYXNzd29yZA==
